// Code generated by MockGen. DO NOT EDIT.
// Source: /home/raramuri/repo/go/src/zopsmart/gofr-curd/service/interface.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	model "zopsmart/gofr-curd/model"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockProductservice is a mock of Productservice interface.
type MockProductservice struct {
	ctrl     *gomock.Controller
	recorder *MockProductserviceMockRecorder
}

// MockProductserviceMockRecorder is the mock recorder for MockProductservice.
type MockProductserviceMockRecorder struct {
	mock *MockProductservice
}

// NewMockProductservice creates a new mock instance.
func NewMockProductservice(ctrl *gomock.Controller) *MockProductservice {
	mock := &MockProductservice{ctrl: ctrl}
	mock.recorder = &MockProductserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductservice) EXPECT() *MockProductserviceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockProductservice) GetByID(ctx *gofr.Context, id string) (model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductserviceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductservice)(nil).GetByID), ctx, id)
}
