// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package Stores is a generated GoMock package.
package Stores

import (
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
	model "github.com/shaurya-zopsmart/Gopr-devlopment/model"
)

// MockStoreint is a mock of Storeint interface.
type MockStoreint struct {
	ctrl     *gomock.Controller
	recorder *MockStoreintMockRecorder
}

// MockStoreintMockRecorder is the mock recorder for MockStoreint.
type MockStoreintMockRecorder struct {
	mock *MockStoreint
}

// NewMockStoreint creates a new mock instance.
func NewMockStoreint(ctrl *gomock.Controller) *MockStoreint {
	mock := &MockStoreint{ctrl: ctrl}
	mock.recorder = &MockStoreintMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreint) EXPECT() *MockStoreintMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockStoreint) GetById(Id int, ctx *gofr.Context) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", Id, ctx)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockStoreintMockRecorder) GetById(Id, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockStoreint)(nil).GetById), Id, ctx)
}
