// Code generated by MockGen. DO NOT EDIT.
// Source: gofr-curd/stores (interfaces: Istore)

// Package stores is a generated GoMock package.
package stores

import (
	models "gofr-curd/models"
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockIstore is a mock of Istore interface.
type MockIstore struct {
	ctrl     *gomock.Controller
	recorder *MockIstoreMockRecorder
}

// MockIstoreMockRecorder is the mock recorder for MockIstore.
type MockIstoreMockRecorder struct {
	mock *MockIstore
}

// NewMockIstore creates a new mock instance.
func NewMockIstore(ctrl *gomock.Controller) *MockIstore {
	mock := &MockIstore{ctrl: ctrl}
	mock.recorder = &MockIstoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIstore) EXPECT() *MockIstoreMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockIstore) CreateProduct(arg0 *gofr.Context, arg1 models.Product) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockIstoreMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockIstore)(nil).CreateProduct), arg0, arg1)
}

// DeleteByID mocks base method.
func (m *MockIstore) DeleteByID(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIstoreMockRecorder) DeleteByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIstore)(nil).DeleteByID), arg0, arg1)
}

// GetAllProducts mocks base method.
func (m *MockIstore) GetAllProducts(arg0 *gofr.Context) ([]*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", arg0)
	ret0, _ := ret[0].([]*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockIstoreMockRecorder) GetAllProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockIstore)(nil).GetAllProducts), arg0)
}

// GetProductByID mocks base method.
func (m *MockIstore) GetProductByID(arg0 *gofr.Context, arg1 int) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockIstoreMockRecorder) GetProductByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockIstore)(nil).GetProductByID), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockIstore) UpdateByID(arg0 *gofr.Context, arg1 int, arg2 models.Product) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIstoreMockRecorder) UpdateByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIstore)(nil).UpdateByID), arg0, arg1, arg2)
}
