// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package Services is a generated GoMock package.
package Services

import (
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
	model "github.com/shaurya-zopsmart/Gopr-devlopment/model"
)

// MockServiceint is a mock of Serviceint interface.
type MockServiceint struct {
	ctrl     *gomock.Controller
	recorder *MockServiceintMockRecorder
}

// MockServiceintMockRecorder is the mock recorder for MockServiceint.
type MockServiceintMockRecorder struct {
	mock *MockServiceint
}

// NewMockServiceint creates a new mock instance.
func NewMockServiceint(ctrl *gomock.Controller) *MockServiceint {
	mock := &MockServiceint{ctrl: ctrl}
	mock.recorder = &MockServiceintMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceint) EXPECT() *MockServiceintMockRecorder {
	return m.recorder
}

// GetId mocks base method.
func (m *MockServiceint) GetId(ctx *gofr.Context, Id int) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId", ctx, Id)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetId indicates an expected call of GetId.
func (mr *MockServiceintMockRecorder) GetId(ctx, Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockServiceint)(nil).GetId), ctx, Id)
}
