// Code generated by MockGen. DO NOT EDIT.
// Source: gofr-curd/services (interfaces: Iservice)

// Package services is a generated GoMock package.
package services

import (
	models "gofr-curd/models"
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockIservice is a mock of Iservice interface.
type MockIservice struct {
	ctrl     *gomock.Controller
	recorder *MockIserviceMockRecorder
}

// MockIserviceMockRecorder is the mock recorder for MockIservice.
type MockIserviceMockRecorder struct {
	mock *MockIservice
}

// NewMockIservice creates a new mock instance.
func NewMockIservice(ctrl *gomock.Controller) *MockIservice {
	mock := &MockIservice{ctrl: ctrl}
	mock.recorder = &MockIserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIservice) EXPECT() *MockIserviceMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockIservice) CreateProduct(arg0 *gofr.Context, arg1 models.Product) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockIserviceMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockIservice)(nil).CreateProduct), arg0, arg1)
}

// DeleteByID mocks base method.
func (m *MockIservice) DeleteByID(arg0 *gofr.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIserviceMockRecorder) DeleteByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIservice)(nil).DeleteByID), arg0, arg1)
}

// GetAllProducts mocks base method.
func (m *MockIservice) GetAllProducts(arg0 *gofr.Context) ([]*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", arg0)
	ret0, _ := ret[0].([]*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockIserviceMockRecorder) GetAllProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockIservice)(nil).GetAllProducts), arg0)
}

// GetProductByID mocks base method.
func (m *MockIservice) GetProductByID(arg0 *gofr.Context, arg1 string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockIserviceMockRecorder) GetProductByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockIservice)(nil).GetProductByID), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockIservice) UpdateByID(arg0 *gofr.Context, arg1 string, arg2 models.Product) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIserviceMockRecorder) UpdateByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIservice)(nil).UpdateByID), arg0, arg1, arg2)
}
